/*
 * Copyright 2022 Centre for Computational Geography.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.github.agdturner.course.coding.python;

import io.github.agdturner.course.Course;
import io.github.agdturner.course.Index;
import io.github.agdturner.course.IndexTerm;

/**
 * Python Index Course Page.
 *
 * @author Andy Turner
 */
public class PythonIndex extends Index {

    /**
     * A constant storing the URL of Python 3 Documentation as a String. 
     */
    public final static String PYTHON_DOCS_URL = "https://docs.python.org/3/";

    /**
     * Create a new instance.
     *
     * @param course What {@link #site} is set to.
     * @param filename What {@link #filename} is set to.
     * @param title What {@link #title} is set to.
     * @param label What {@link #label} is set to.
     */
    public PythonIndex(Course course, String filename, String title, String label) {
        super(course, filename, title, label);
        String name;
        String url;
        String description;
        IndexTerm indexTerm;

        name = "Beautiful Soup";
        url = "https://beautiful-soup-4.readthedocs.io/";
        description = "A \"Python\" library for pulling data out of \"HTML\" and "
                + "\"XML\" files";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "PIP";
        url = "https://pip.pypa.io";
        description = "The Package Installer for \"Python\"";
        indexTerm =  new IndexTerm(this, description, url);
        termToIndexTerm.put(name, indexTerm);
        addLowerCaseAlias(url, indexTerm);
        
        name = "Python Package Index";
        url = "https://pypi.org/";
        description = "A repository of software for the Python programming "
                + "language.";
        indexTerm =  new IndexTerm(this, description, url);
        termToIndexTerm.put(name, indexTerm);
        addAliasAndLowerCase(name, "PyPi", indexTerm);
                
        name = "PyQGIS";
        url = "https://qgis.org/pyqgis/";
        description = "QGIS Python API";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "PyQGIS Developer Cookbook";
        url = "https://docs.qgis.org/latest/en/docs/pygqis_developer_cookbook/";
        description = "A tutorial and a reference guide to the PyQGIS API";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python array";
        url = getPythonDocsLibraryURL("array.html");
        description = "A \"standard library\" module that defines an object "
                + "type which can compactly represent a sequence of values all "
                + "of the same type. An array behaves like a \"list\", except "
                + "that the type of objects stored in them is "
                + "restricted/constrained";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python break";
        url = getPythonDocsReferenceURL("simple_stmts.html#break");
        description = "A \"keyword\" that terminates the nearest enclosing "
                + "loop, skipping the optional 'else' clause if the loop has "
                + "one";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python builtins";
        url = getPythonDocsLibraryURL("builtins.html");
        description = "An always loaded module that provides direct access to "
                + "all 'built-in' identifiers";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));
        aliasToTerm.put("builtins module", name);

        name = "Python Built-in Constants";
        url = getPythonDocsLibraryURL("constants.html#built-in-consts");
        description = "Constants that are always available";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));
        aliasToTerm.put("built-in constant", name);

        name = "Python Built-in Exceptions";
        url = getPythonDocsLibraryURL("exceptions.html");
        description = "Are generated by the interpreter or a \"built-in "
                + "function\" when an error is encountered";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));
        aliasToTerm.put("built-in exception", name);

        name = "Python Built-in Functions";
        url = getPythonDocsLibraryURL("functions.html#built-in-funcs");
        description = "Functions and types that are always available";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));
        aliasToTerm.put("built-in function", name);

        name = "Python Built-in Types";
        url = getPythonDocsLibraryURL("stdtypes.html");
        description = "A \"Standard library\" numerics, sequences, mappings, "
                + "classes, instances and exceptions that are 'built-in' to "
                + "the interpreter";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));
        aliasToTerm.put("built-in type", name);

        name = "Python continue";
        url = getPythonDocsReferenceURL("simple_stmts.html#continue");
        description = "A \"keyword\" that continues with the next cycle of the "
                + "nearest enclosing loop. When continue passes control out of "
                + "a \"try\" statement with a 'finally' clause, that finally "
                + "clause is executed before starting the next loop cycle";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python csv";
        url = getPythonDocsReferenceURL("simple_stmts.html#continue");
        description = "A \"standard library\" module for handling data in a "
                + "\"CSV file format\"";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python decimal";
        url = getPythonDocsLibraryURL("decimal.html");
        description = "A \"standard library\" module providing support for "
                + "fast correctly rounded decimal floating point arithmetic";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python delimiters";
        url = getPythonDocsReferenceURL("lexical_analysis.html#delimiters");
        description = "A \"string\" that separates parts";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python dict";
        url = getPythonDocsLibraryURL("stdtypes.html#dict");
        description = "A mapping object that maps unique keys to values";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python docstring";
        url = "https://peps.python.org/pep-0257/#what-is-a-docstring";
        description = "A string literal comment that occurs as the first "
                + "statement in a module, function, class, or method "
                + "definition. This becomes the '__doc__' attribute of "
                + "that object";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python bytes";
        url = getPythonDocsLibraryURL("stdtypes.html#bytes");
        description = "A container storing an immutable sequence of integers "
                + "in the range [0, 255]";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python bytearray";
        url = getPythonDocsLibraryURL("stdtypes.html#bytearray");
        description = "A mutable counterpart to a \"Python byte\"";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python dir";
        url = getPythonDocsLibraryURL("functions.html#dir");
        description = "A function that: without arguments, returns the list of "
                + "names in the current local scope; and, with an argument, "
                + "attempts to return a list of valid attributes for that "
                + "object";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python doctest";
        url = getPythonDocsLibraryURL("doctest.html");
        description = "A \"standard library\" module that can be used to "
                + "search for text that looks like interactive Python "
                + "sessions, and then executes those sessions to verify "
                + "that they work as shown";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));
                
        name = "Python for";
        url = getPythonDocsReferenceURL("compound_stmts.html#for");
        description = "Used to iterate over the elements of a sequence";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python fractions";
        url = getPythonDocsLibraryURL("fractions.html");
        description = "A \"standard library\" module providing support for "
                + "rational number arithmetic";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python help";
        url = getPythonDocsLibraryURL("functions.html#help");
        description = "A function that starts the help system";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python if";
        url = getPythonDocsReferenceURL("compound_stmts.html#if");
        description = "A compound statement used for conditional execution";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python input";
        url = getPythonDocsLibraryURL("functions.html#input");
        description = "A \"builtins module\" function that reads a line from "
                + "standard input, converts it to a \"string\" (stripping the "
                + "trailing newline), and returns that string";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python import";
        url = getPythonDocsReferenceURL("simple_stmts.html#import");
        description = "A statement for importing modules";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python io";
        url = getPythonDocsLibraryURL("io.html");
        description = "A \"standard library\" module the provides the main "
                + "facilities for dealing with various types of input and "
                + "output";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python json";
        url = getPythonDocsLibraryURL("json.html");
        description = "A \"standard library\" module for handling data in "
                + "\"JSON\" format";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python keyword";
        url = getPythonDocsReferenceURL("lexical_analysis.html#keywords");
        description = "A reserved word that cannot be used as an "
                + "ordinary identifier (names of variable, function, class, "
                + "module or package)";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));
        aliasToTerm.put("keyword", name);

        name = "Python lambda";
        url = getPythonDocsReferenceURL("expressions.html#lambda");
        description = "An expression used to create anonymous functions";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python len";
        url = getPythonDocsLibraryURL("functions.html#len");
        description = "A function for getting the length (the number of items) "
                + "of an object";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python list";
        url = getPythonDocsLibraryURL("stdtypes.html#lists");
        description = "A mutable sequence, typically used to store collections "
                + "of homogeneous items";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));
        aliasToTerm.put("list", name);

        name = "Python match";
        url = getPythonDocsReferenceURL("compound_stmts.html#the-match-statement");
        description = "A statement used for pattern matching";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python math";
        url = getPythonDocsReferenceURL("math.html");
        description = "provides access to the mathematical functions defined "
                + "by the C standard";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python MemoryError";
        url = getPythonDocsLibraryURL("exceptions.html#MemoryError");
        description = "a \"built-in exception\" raised when an operation runs out of "
                + "\"memory\" but the situation may still be rescued (by deleting "
                + "some objects)";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python Module Index";
        url = PYTHON_DOCS_URL + "py-modindex.html";
        description = "an index of \"standard library\" modules";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python NameError";
        url = getPythonDocsLibraryURL("exceptions.html#NameError");
        description = "an \"built-in exception\" raised when a local or global name is "
                + "not found";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python Numeric Types";
        url = getPythonDocsLibraryURL("stdtypes.html#numeric-types-int-float-complex");
        description = "are of three distinct types: integers, floating point "
                + "numbers, and complex numbers";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python open";
        url = getPythonDocsLibraryURL("functions.html#open");
        description = "a \"builtins module\" function to open a file and "
                + "return a corresponding file object";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python operator";
        url = getPythonDocsLibraryURL("operator.html");
        description = "a \"standard library\" module that exports a set of "
                + "functions corresponding to the intrinsic operators of "
                + "Python";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python print";
        url = getPythonDocsLibraryURL("functions.html#print");
        description = "a \"builtins module\" function for printing to the "
                + "screen";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python random";
        url = getPythonDocsLibraryURL("random.html");
        description = "a \"standard library\" module that implements pseudo-random "
                + "number generators for various distributions";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python range";
        url = getPythonDocsLibraryURL("stdtypes.html#ranges");
        description = "an immutable sequence of numbers, commonly used for "
                + "looping a specific number of times in for loops";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python repr";
        url = getPythonDocsLibraryURL("functions.html#repr");
        description = "a \"builtins module\" function for getting "
                + "printable representation of an object";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python Requests";
        url = "https://requests.readthedocs.io/";
        description = "a third party HTTP library for Python";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python set";
        url = getPythonDocsLibraryURL("stdtypes.html#set");
        description = "an unordered collection of distinct hashable objects. "
                + "A hashable object has a hash value which must be the same "
                + "for objects regarded as equal";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python Standard Library";
        url = getPythonDocsLibraryURL("");
        description = "the functionality that is included in Python "
                + "distributions as standard and it's reference manual";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));
        aliasToTerm.put("standard library", name);

        name = "Python str";
        url = getPythonDocsLibraryURL("functions.html#func-str");
        description = "a \"builtins module\" function for creating a "
                + "\"string\"";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python string";
        url = getPythonDocsLibraryURL("stdtypes.html#textseq");
        description = "a standard type and immutable sequence of \"Unicode\" "
                + "code points";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));
        aliasToTerm.put("string", name);

        name = "Python SyntaxError";
        url = getPythonDocsLibraryURL("exceptions.html#SyntaxError");
        description = "a \"built-in exception\" raised when the parser encounters a "
                + "\"syntax error\"";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python sys";
        url = getPythonDocsLibraryURL("sys.html");
        description = "a \"standard library\" module that provides access "
                + "to some variables used or maintained by the interpreter and "
                + "to functions that interact strongly with the interpreter";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python SystemError";
        url = getPythonDocsLibraryURL("exceptions.html#SystemError");
        description = "a \"built-in exception\" raised when the interpreter "
                + "encounters an internal error";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));
        
        name = "Python time";
        url = getPythonDocsLibraryURL("time.html");
        description = "a \"standard library\" module providing various "
                + "time-related functions";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python tk";
        url = getPythonDocsLibraryURL("tk.html");
        description = "documentation about developing \"GUIs\" with "
                + "\"tkinter\"";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python tkinter";
        url = getPythonDocsLibraryURL("tkinter.html");
        description = "a \"standard library\" module providing an interface to "
                + "the Tcl/Tk \"GUI\" toolkit";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));
        aliasToTerm.put("tkinter", name);

        name = "Python try";
        url = getPythonDocsReferenceURL("compound_stmts.html#try");
        description = "a statement specifies exception handlers and/or cleanup "
                + "code for a code block";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));
        aliasToTerm.put("try", name);

        name = "Python tuple";
        url = getPythonDocsLibraryURL("stdtypes.html#tuples");
        description = "an immutable sequences, typically used to store "
                + "collections of heterogeneous data";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python type";
        url = getPythonDocsLibraryURL("functions.html#type");
        description = "a \"builtins module\" function for getting the type "
                + "of an identifier";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python TypeError";
        url = getPythonDocsLibraryURL("exceptions.html#TypeError");
        description = "a \"built-in exception\" raised when an operation or "
                + "function is applied to an object of inappropriate type";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python unittest";
        url = getPythonDocsLibraryURL("unittest.html");
        description = "a \"standard library\" module providing tools for "
                + "constructing and running tests.";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python venv";
        url = getPythonDocsLibraryURL("venv.html");
        description = "a \"standard library\" module that supports creating "
                + "lightweight <a href=\"https://docs.python.org/3/glossary.html#term-virtual-environment\">"
                + "virtual environments</a>, each with their own "
                + "independent set of Python packages installed in their site "
                + "directories";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python while";
        url = getPythonDocsReferenceURL("compound_stmts.html#while");
        description = "a compound statement used for repeated execution as "
                + "long as an expression evaluates as true";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python yield";
        url = getPythonDocsReferenceURL("simple_stmts.html#yield");
        description = "a keyword used in a statement or expression that "
                + "returns something from a function whilst allowing further "
                + "expressions in the function to be evaluated";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python zip";
        url = getPythonDocsLibraryURL("functions.html#zip");
        description = "a \"builtins module\" function that iterates over "
                + "multiple iterables in parallel, producing tuples with an "
                + "item from each one";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));

        name = "Python ZeroDivisionError";
        url = getPythonDocsLibraryURL("exceptions.html#ZeroDivisionError");
        description = "a \"built-in exception\" raised when the second argument of a "
                + "division or modulo operation is zero";
        termToIndexTerm.put(name, new IndexTerm(this, description, url));
    }

    /**
     * @param article Appended to complete the URL String. 
     * @return {@link #PYTHON_DOCS_URL} + article;
     */
    public static final String getPythonDocsLibraryURL(String article) {
        return PYTHON_DOCS_URL + "library/" + article;
    }

    /**
     * @param article Appended to complete the URL String. 
     * @return {@link #PYTHON_DOCS_URL} + article;
     */
    public static final String getPythonDocsReferenceURL(String article) {
        return PYTHON_DOCS_URL + "reference/" + article;
    }
}
