/*
 * Copyright 2023 Centre for Computational Geography.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.github.agdturner.course.pages;

import io.github.agdturner.core.Environment;
import io.github.agdturner.core.SectionID;
import io.github.agdturner.core.Strings;
import io.github.agdturner.course.CoursePage;
import io.github.agdturner.course.Course;
import uk.ac.leeds.ccg.web.io.Web_ContentWriter;

/**
 * Course Home Page.
 *
 * @author Andy Turner
 */
public abstract class CourseHome extends CoursePage {

    /**
     * Create a new instance.
     *
     * @param course What {@link #site} is set to.
     */
    public CourseHome(Course course) {
        super(course, "home",
                course.getCourseCode() + ": " + course.courseName,
                "Home");
    }

    @Override
    public String getMainContent() {
        StringBuilder sb = new StringBuilder();
        getIntroduction(sb);
        getSyllabus(sb);
        getExpectations(sb);
        getLearningJourney(sb);
        getPlatform(sb);
        return sb.toString();
    }

    /**
     * Introduction.
     *
     * @param sb The StringBuilder to append to.
     */
    public abstract void getIntroduction(StringBuilder sb);

    /**
     * Introduction 0.
     *
     * @param sb The StringBuilder to append to.
     * @return SectionID for indexing terms.
     */
    public SectionID getIntroduction0(StringBuilder sb) {
        sb.append("<div>\n");
        SectionID sid = addSection("Introduction", sb);
        w.addPST(sb,
                """
                This website is an open educational resource to help researchers 
                learn to program using the
                """);
        sb.append(index.getReference("Python"));
        sb.append(" programming language.");
        return sid;
    }

    /**
     * Maintainer.
     *
     * @param sb The StringBuilder to append to.
     * @param sid For indexing terms.
     */
    public void getMaintainer(StringBuilder sb, SectionID sid) {
        sb.append(" It is maintained by ");
        sb.append(Web_ContentWriter.getLink(
                Environment.HTTPS_AGDTURNER_GITHUB_IO,
                "Andy Turner"));
//        w.addPST(sb, "The website is maintained by the ");
//        sb.append(Web_ContentWriter.getLink(
//                Environment.HTTPS_ARC_LEEDS_AC_UK_ABOUT_TEAM,
//                "Research Computing Team"));
//        sb.append(" at the ");
//        sb.append(Web_ContentWriter.getLink(Environment.HTTPS_WWW_LEEDS_AC_UK,
//                "University of Leeds"));
        sb.append(" and is based on learning resources developed for GEOG5990, "
                + "GEOG5991 and GEOG5995 modules taught at ");
        sb.append(Web_ContentWriter.getLink(
                Environment.HTTPS_AGDTURNER_GITHUB_IO,
                "The University of Leeds"));
        sb.append(" (the old course materials may still be available via: ");
        sb.append(Web_ContentWriter.getLink(
                Environment.HTTPS_WWW_GEOG_LEEDS_AC_UK_COURSES_COMPUTING,
                Environment.HTTPS_WWW_GEOG_LEEDS_AC_UK_COURSES_COMPUTING));
        w.addPET(sb, ").");
        w.addPST(sb, "The website is generated by some bespoke Java code ");
        sb.append(" which generates a site based on standard ");
        sb.append(Web_ContentWriter.getLink(
                Environment.getWikipediaURL("HTML"), "HTML"));
        sb.append(", ");
        sb.append(Web_ContentWriter.getLink(
                Environment.getWikipediaURL("CSS"), "CSS"));
        sb.append(" and ");
        sb.append(Web_ContentWriter.getLink(
                Environment.getWikipediaURL("JavaScript"), "JavaScript"));
        sb.append(". Please raise issues/submit pull requests via the ");
        sb.append(Web_ContentWriter.getLink(
                Environment.AGDTURNER_GITHUB_IO_REPO,
                "agdturner-github-io GitHub repository"));
        sb.append(" (which contains the generated output) and/or the ");
        sb.append(Web_ContentWriter.getLink(
                Environment.AGDTURNER_GITHUB_IO_GENERATOR_REPO,
                "agdturner-github-io-generator GitHub repository"));
        w.addPET(sb, " (the Java that generates the website content) to help.");
    }

    /**
     * Navigation.
     *
     * @param sb The StringBuilder to append to.
     * @param sid For indexing terms.
     */
    public void getNavigation(StringBuilder sb, SectionID sid) {
        w.addP(sb,
                """
                Each page in the site has a button at the top to change between 
                a lighter and darker page style, then a navigation section that
                links to the other pages. The pages are sequential and also link
                to the next page after the pages main content.
                """);
        w.addPST(sb, "The ");
        sb.append(getLink(index, "index", "link", ""));
        w.addPET(sb,
                """
                 page is a glossary of terms that links back to page sections 
                where terms are used.
                """);
        w.addPST(sb, "The ");
        sb.append(getLink(references, "references", "link", ""));
        w.addPET(sb,
                """
                 page is a useful list of references and links to other
                resources.
                """);
        w.addP(sb,
                """
                Pages with multiple sections have a contents towards the top
                that links to those sections.
                """);
        w.addP(sb,
                """
                To get the most from the learning resources, work your way 
                through the pages and undertake practical exercises as directed.
                """);
    }

    /**
     * Introduction N.
     *
     * @param sb The StringBuilder to append to.
     * @param sid For indexing terms.
     */
    public void getIntroductionN(StringBuilder sb, SectionID sid) {
        sb.append("</div>\n");
    }

    /**
     * For detailing the syllabus.
     *
     * @param sb The StringBuilder to append to.
     */
    public abstract void getSyllabus(StringBuilder sb);

    /**
     * For detailing the first part of the syllabus.
     *
     * @param sb The StringBuilder to append to.
     * @return SectionID for indexing terms.
     */
    public SectionID getSyllabus0(StringBuilder sb) {
        sb.append("<div>\n");
        SectionID sid = addSection("Syllabus", sb);
        return sid;
    }

    /**
     * For detailing the last part of the syllabus.
     *
     * @param sb The StringBuilder to append to.
     * @param sid For indexing terms.
     */
    public void getSyllabusN(StringBuilder sb, SectionID sid) {
        sb.append("</div>\n");
    }

    /**
     * For detailing the expectations.
     *
     * @param sb The StringBuilder to append to.
     */
    public abstract void getExpectations(StringBuilder sb);

    /**
     * For detailing the first part of the expectations.
     *
     * @param sb The StringBuilder to append to.
     * @return SectionID for indexing terms.
     */
    public SectionID getExpectations0(StringBuilder sb) {
        sb.append("<div>\n");
        SectionID sid = addSection("Expectations", sb);
        w.addP(sb, "You will learn about:");
        w.addULST(sb);
        return sid;
    }

    /**
     * For detailing the expectations.
     *
     * @param sb The StringBuilder to append to.
     * @param sid For indexing terms.
     */
    public abstract void getExpectations1(StringBuilder sb, SectionID sid);

    /**
     * For detailing the last part of the expectations.
     *
     * @param sb The StringBuilder to append to.
     * @param sid For indexing terms.
     */
    public void getExpectationsN(StringBuilder sb, SectionID sid) {
        w.addP(sb,
                """
                There are some key concepts which may take a few attempts to get
                used to and comprehensively understand.
                """);
        sb.append("</div>\n");
    }

    /**
     * For detailing the learning journey.
     *
     * @param sb The StringBuilder to append to.
     */
    public abstract void getLearningJourney(StringBuilder sb);

    /**
     * For detailing the first part of the learning journey section.
     *
     * @param sb The StringBuilder to append to.
     * @return SectionID for indexing terms.
     */
    public SectionID getLearningJourney0(StringBuilder sb) {
        sb.append("<div>\n");
        SectionID sid = addSection("The Learning Journey", sb);
        w.addP(sb,
                "Develop your understanding through practise and by reading.");
        w.addP(sb,
                """
                Be experimental - test your understanding by testing things do
                what you expect. If things do not do what you expect, try to
                understand why. Encountering an exception error fault or failure 
                is a learning opportunity that should not be ignored!
                """);
        return sid;
    }

    /**
     * For detailing the last part of the learning journey section.
     *
     * @param sb The StringBuilder to append to.
     * @param sid For indexing terms.
     */
    public void getLearningJourneyN(StringBuilder sb, SectionID sid) {
        String courseName = getCourse().courseType;
        String courseNameUC = Strings.toUpperCaseFirstLetter(courseName);
        w.addPST(sb,
                """
                Try to enjoy the learning journey, the challenges and the
                rewards. Learning to program and learning
                """);
        sb.append(index.getReference(courseName, courseNameUC));
        w.addPET(sb, " is empowering!");
        sb.append("</div>\n");
    }

    /**
     * For detailing the platform section.
     *
     * @param sb The StringBuilder to append to.
     */
    public abstract void getPlatform(StringBuilder sb);

    /**
     * For detailing the first part of the platform section.
     *
     * @param sb The StringBuilder to append to.
     * @return SectionID for indexing terms.
     */
    public SectionID getPlatform0(StringBuilder sb) {
        SectionID sid = addSection("Platform/Software", sb);
        w.addPST(sb, "All the software used in this course is ");
        sb.append(index.getReference("Free and Open Source Software"));
        sb.append(" (FOSS) - available to download and install on ");
        sb.append(index.getReference("Linux"));
        sb.append(", ");
        sb.append(index.getReference("Microsoft Windows"));
        sb.append(", and ");
        sb.append(index.getReference("MacOS"));
        w.addPET(sb, ".");
        return sid;
    }

    /**
     * For detailing the last part of the platform section.
     *
     * @param sb The StringBuilder to append to.
     * @param sid For indexing terms.
     */
    public void getPlatformN(StringBuilder sb, SectionID sid) {
        sb.append("</div>\n");
    }

    /**
     * @return {@code (Course) site).
     */
    @Override
    public Course getCourse() {
        return (Course) site;
    }
}
